# Generated by Django 3.0.3 on 2020-03-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priortime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorsheet',
            name='is_billable',
            field=models.CharField(choices=[('B', 'B'), ('N', 'N'), ('L', 'L')], max_length=1),
        ),
    ]
