# Generated by Django 2.2 on 2019-04-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manager_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
