# Generated by Django 2.2 on 2019-06-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='C:\\Users\\gpanwar2\\Desktop\\Django\\localtimesheet\\timesheet\\src\\live-static\\media-root/profile/pics/noimage.png', upload_to='img/profilepics'),
        ),
    ]
