# Generated by Django 2.2 on 2019-06-09 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20190609_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
    ]
