# Generated by Django 2.2 on 2019-06-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='/profilepics/noimage.png', upload_to='profilepics/'),
        ),
    ]
