# Generated by Django 2.2 on 2019-08-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20190609_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='/profilepics/images.png', upload_to='profilepics/'),
        ),
    ]
