# Generated by Django 3.0 on 2021-01-11 20:26

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20190801_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='/profilepics/images.png', upload_to=userprofile.models.user_directory_path),
        ),
    ]
