# Generated by Django 2.2 on 2019-09-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='leaveid',
            field=models.CharField(default='EL', max_length=20),
        ),
        migrations.AlterField(
            model_name='applyleave',
            name='user',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
