# Generated by Django 2.2 on 2019-09-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20190902_0953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applyleave',
            unique_together={('leaveid', 'date', 'user')},
        ),
    ]
