# Generated by Django 2.2 on 2019-08-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='sum_hours',
        ),
    ]
