# Generated by Django 2.2 on 2019-09-02 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0002_remove_timesheet_sum_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['tstamp']},
        ),
    ]
