# Generated by Django 2.2 on 2019-09-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0003_auto_20190902_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='sum_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
