# Generated by Django 2.2 on 2019-10-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0004_timesheet_sum_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='user_project',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
