# Generated by Django 3.0.3 on 2020-03-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0005_timesheet_user_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='is_billable',
            field=models.CharField(choices=[('B', 'B'), ('N', 'N'), ('L', 'L')], max_length=1),
        ),
    ]
